[app]
GOOGLE_API_KEY = "AlzaSyA0y4AhrNFi2o6c2NPQRTjHPpeiRcyZHpg"
MONGODB_URI = "mongodb+srv://salvatierralonso29:juanalonso@jasr.cyhellz.mongodb.net/"
USER = "salvatierralonso29"
COHERE_API_KEY = "xmhQ2yX73tDwSDdTX1pUc1bRnqkAHUaZXi1LH0PA"

[b2]
B2_BUCKET_NAME = "PC2-CC-JASR"
B2_READ_KEY_ID = "005c691f1cf7a240000000004"
B2_READ_APPLICATION_KEY = "K005tdLybKn1GWYUEXJaFUJ8651V4jE"
B2_WRITE_KEY_ID = "005c691f1cf7a240000000005"
B2_WRITE_APPLICATION_KEY = "K005JOErPE8scgfyeRhgbErvB3Mibc4"

